server:
  port: 8084

spring:
  application:
    name: project-service
  datasource:
    url: jdbc:postgresql://localhost:5432/coder_ride_project
    username: coderride
    password: password
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

